### ISSUE TITLE
Add `--terse` option to `amdahl` to make it easier to parse the output 

### ISSUE THREAD

**Issue by ocaisa** [hpc-carpentry/old-hpc-workflows#6]
PR should go to https://github.com/ocaisa/amdahl

**Comment by mikerenfro** [comment]
PR https://github.com/ocaisa/amdahl/pull/6 created to address this.

**Comment by ocaisa** [comment]
Thanks @mikerenfro , that is now merged and included in the [latest release of Amdahl](https://github.com/ocaisa/amdahl/releases/tag/v0.2.1)
